### ISSUE TITLE
IndexError when emojis in input

### ISSUE THREAD

**Issue by nthomsencph** [KennethEnevoldsen/spacy-wrap#82] opened 2022-12-11 02:09 UTC
## How to reproduce the behaviour

```python
import spacy
import spacy_wrap
nlp = spacy.blank("en")

# specify model from the hub
config = {"model": {"name": "dslim/bert-base-NER"}}
# add it to the pipe
nlp.add_pipe("token_classification_transformer", config=config)

doc = nlp("My name is Wolfgang 🚀 and I live in Berlin.")
```

## Your Environment

* spacy-wrap Version Used: spacy_wrap-1.2.0-py2.py3-none-any.whl
* Operating System: MacOS, Apple M1, Ventura 13.0.1
* Python Version Used: 3.10.6
* spaCy Version Used: 3.4.3
* Environment Information: poetry
* Torch version: 1.13.0-cp310
torch = {url = "https://files.pythonhosted.org/packages/79/b3/eaea3fc35d0466b9dae1e3f9db08467939347b3aaa53c0fd81953032db33/torch-1.13.0-cp310-none-macosx_11_0_arm64.whl"}

(Had to set torch manually because spacy-wrap fails to install on Mac with the default torch version. Specifically, the dependency `nvidia-cublas-cu11` returns a RuntimeError with "Unable to find installation candidates for nvidia-cublas-cu11 (11.10.3.66)". No distributions available for Mac, see https://pypi.org/project/nvidia-cublas-cu11/11.10.3.66/#files )

Above example yields an IndexError in TokenClassificationTransformer.convert_to_token_predictions(data, aggregation_strategy, labels)
```
      305 logits = data.model_output.logits[0]
      306 for align in data.align:
      307     # aggregate the logits for each token
--> 308     agg_token_logits = agg(logits[align.data[:, 0]])
      309     token_probabilities_ = {
      310         "prob": softmax(agg_token_logits).round(decimals=3),
      311         "label": labels,
      312     }
      313     token_probabilities.append(token_probabilities_)

IndexError: index 0 is out of bounds for axis 1 with size 0
```
Issue is the same with other models. Tried `saattrupdan/nbailab-base-ner-scandi`.

Tests with transformers pipeline works with same models.
```python
from transformers import pipeline
pipe = pipeline(model="dslim/bert-base-NER")
res = pipe("My name is Wolfgang 🚀 and I live in Berlin.")
[e["word"] for e in res]
# ['Wolfgang', '🚀', 'Berlin']
```

**Comment by KennethEnevoldsen** [comment] 2022-12-12 09:55
Thanks for reporting this. So there seem to be two problems, 
1) with the installation (I should be able to test this locally), but it might be an error inherited from spacy-transformers (if it is, I will create an issue on their repo)
2) Seems like the indexerror might be caused by the emoji - which causes a mismatch between the spacy tokens and the wordpiece tokens of the model - I thought I had handled most case, might have been wrong. Will let you know what I can do about it.

Will probably take a look at some time during the week

**Comment by nthomsencph** [comment] 2022-12-12 09:59
Thanks. Also for building this great tool! 🚀

**Comment by KennethEnevoldsen** [comment] 2022-12-23 18:20
Minor update, I have looked into this. It seems like it is caused by the rocket leading to an UNK token, which is not aligned with the spacy tokens. In this case it can be estimated from context, but in even slightly more complex (repeating UNK tokens) it breaks down. One solution is to simply skip UNK tokens (I would ideally like to avoid that).

I have created a [discussion](https://github.com/explosion/spaCy/discussions/12023) on spaCy's discussion forum as well. Feel free to chime in if you have any suggestions one how to resolve the problem.

**Comment by nthomsencph** [comment] 2022-12-23 18:25
Great. I'll follow along in the SpaCy discussion 👌

**Comment by KennethEnevoldsen** [comment] 2023-01-04 12:53
As discussed in the [discussion thread](https://github.com/explosion/spaCy/discussions/12023) switching to the latest version of `spacy-transformers` resolve the issue:

```
pip install git+https://github.com/explosion/spacy-transformers
```

This leads to the intended output:
```python
import spacy
import spacy_wrap
nlp = spacy.blank("en")

# specify model from the hf hub
config = {"model": {"name": "dslim/bert-base-NER"}}

# add it to the pipe
nlp.add_pipe("token_classification_transformer", config=config)

# test it on two samples
doc = nlp("My name is Wolfgang 🚀 and I live in Berlin.")
# [('Wolfgang 🚀', 'PER'), ('Berlin', 'LOC')]

print([(ent.text, ent.label_) for ent in doc.ents])
doc = nlp("My name is Wolfgang 🚀🚀 🚀 and I live in Berlin.")
print([(ent.text, ent.label_) for ent in doc.ents])
# [('Wolfgang 🚀🚀 🚀', 'PER'), ('Berlin', 'LOC')]
```

I will leave this issue open until I can specify the new spacy transformers as a requirement (it is only in development). I will not create a hotfix for older versions of spacy-transformers (though if that is a requirement, a code snippet exists for it over on the discussion thread, and a PR would be very welcome).

**Comment by nthomsencph** [comment] 2023-01-04 19:35
Perfect! Thanks for helping out.

**Comment by KennethEnevoldsen** [comment] 2023-01-30 21:43
Hi, @nthomsencph latest version of spacy-wrap has now fixed this problem!

**Closed by KennethEnevoldsen** 2023-01-30 21:43 UTC
Labels: bug
